# Name of website
title: NOVAthesis LaTeX template

# Description of website
description: A LaTeX template for thesis, dissertations and similar monography-like documents

# Your name to show in the footer
author: João Lourenço

#avatar: "/assets/img/avatar-icon.png"

title-img: /novathesis-files/Images/novathesis_cover_image.jpg

theme: jekyll-theme-minimal